name: Release Drafter
on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@73b95fa1c286dfd6802a4f949b07dad6149f2b0f # v7.5.0
        with:
          # This token is generated automatically by default in GitHub Actions: no need to create it manually
          token: ${{ secrets.GITHUB_TOKEN }}
